name: FreeRDP
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cloudflare
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          cloudflared tunnel --url tcp://localhost:3389 --token ${{ secrets.CLOUDFLARE_AUTH_TOKEN }} &
      - name: Keep Alive
        run: sleep 21600
