name: FreeRDP-Zorin
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Desktop and RDP
        run: |
          sudo apt update
          # Install XFCE Desktop and XRDP Server
          sudo apt install -y xfce4 xfce4-goodies xrdp
          # Fix password for the 'runner' user
          echo "$USER:Zorin123" | sudo chpasswd
          echo xfce4-session > ~/.xsession
          sudo systemctl enable xrdp
          sudo service xrdp start

      - name: Setup Cloudflare Tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          # This creates the link you need to connect
          cloudflared tunnel --url tcp://localhost:3389 --token ${{ secrets.CLOUDFLARE_AUTH_TOKEN }} &

      - name: Keep Alive (6 Hours)
        run: sleep 21600
